module.exports = {
   "stats": {
      "seedCount": 14,
      "roles": {
         "farmer": 1,
         "landlord": 2,
         "seedProducer": 3
      },
      "bu": "QmYLirwZinjC4x8RwcJPkLotVwWPKNJqsxLSysXbYBL2G4",
      "bi": 50731401,
      "prices": {
         "bundles": {
            "asiaBundle": 216,
            "africaBundle": 108,
            "afghanistanBundle": 72,
            "jamaicaBundle": 144,
            "mexicoBundle": 54,
            "southAmericaBundle": 36
         },
         "waterPlants": {
            "LVL1": {
               "price": 100000,
               "water": 30,
               "token": 1000
            },
            "LVL2": {
               "price": 100000,
               "water": 45,
               "token": 1000
            },
            "LVL3": {
               "price": 100000,
               "water": 75,
               "token": 1000
            },
            "LVL4": {
               "price": 100000,
               "water": 120,
               "token": 1000
            },
            "LVL5": {
               "price": 100000,
               "water": 180,
               "token": 1000
            },
            "LVL6": {
               "price": 100000,
               "water": 255,
               "token": 1000
            },
            "LVL7": {
               "price": 100000,
               "water": 345,
               "token": 1000
            },
            "LVL8": {
               "price": 100000,
               "water": 450,
               "token": 1000
            },
            "LVL9": {
               "price": 100000,
               "water": 570,
               "token": 1000
            },
            "LVL10": {
               "price": 100000,
               "water": 705,
               "token": 1000
            }
         },
         "timeBooster": {
            "lvl1": {
               "buds": 10,
               "boost": 5
            },
            "lvl2": {
               "buds": 50,
               "boost": 10
            },
            "lvl3": {
               "buds": 210,
               "boost": 15
            },
            "lvl4": {
               "buds": 750,
               "boost": 20
            },
            "lvl5": {
               "buds": 2000,
               "boost": 25
            },
            "lvl6": {
               "buds": 2500,
               "boost": 30
            }
         },
         "joints": {
            "splif": 50,
            "joint": 200,
            "cone": 1000,
            "kiefJoint": 2500,
            "waxJoint": 5000,
            "blunt": 10000
         },
         "recollector": {
            "lvl1": {
               "buds": 20,
               "boost": 50
            },
            "lvl2": {
               "buds": 40,
               "boost": 60
            },
            "lvl3": {
               "buds": 60,
               "boost": 70
            },
            "lvl4": {
               "buds": 80,
               "boost": 80
            },
            "lvl5": {
               "buds": 100,
               "boost": 90
            },
            "lvl6": {
               "buds": 150,
               "boost": 100
            }
         },
         "land": {
            "asia": {
               "price": 108,
               "token": 1080
            },
            "africa": {
               "price": 54,
               "token": 540
            },
            "afghanistan": {
               "price": 36,
               "token": 360
            },
            "southAmerica": {
               "price": 13,
               "token": 130
            },
            "jamaica": {
               "price": 71,
               "token": 710
            },
            "mexico": {
               "price": 26,
               "token": 260
            }
         }
      },
      "supply": {
         "land": {
            "asia": 0,
            "asiaC": 40,
            "africa": 289,
            "africaC": 11,
            "afghanistan": 483,
            "afghanistanC": 17,
            "southAmerica": 1442,
            "southAmericaC": 58,
            "jamaica": 91,
            "jamaicaC": 19,
            "mexico": 731,
            "mexicoC": 19
         }
      },
      "farmers": 49,
      "farmerList": [
         "qwoyn",
         "r0um3n1987",
         "boyobevan",
         "academialibertad",
         "abztraxxx",
         "audiomancer",
         "cryptounicorn420",
         "dolp",
         "xplora4253",
         "ricarox",
         "edtorr704",
         "marcoss21",
         "foxon",
         "meanbees",
         "degranoengrano",
         "ibanezense",
         "ejmh",
         "toxicmen01",
         "cratic",
         "criptojones",
         "bigkidstuff",
         "dominic23",
         "electru",
         "lozadakb",
         "hodltoday",
         "fdeflash",
         "pedroozj",
         "facugaba",
         "luisveco88",
         "aries02",
         "medicenw1",
         "quefe",
         "mejiasclaudia",
         "cadawg",
         "ecuaminte",
         "abrockman",
         "supremdsm",
         "darthslaver",
         "juanchuzx",
         "dobro2020",
         "dantejcs",
         "the-mister7",
         "reward.app",
         "oblivioncubed",
         "yoclensavilan",
         "elprutest",
         "khan.dayyanz",
         "xbladex",
         "cireth"
      ]
   },
   "bal": {
      "r": 0,
      "c": 0,
      "b": 0,
      "p": 0
   },
   "refund": [],
   "users": {
      "qwoyn": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0.0001,
         "MOTAstake": 0
      },
      "r0um3n1987": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "boyobevan": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "academialibertad": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 1,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 1,
         "seedCount": 1,
         "seeds": [
            {
               "name": "Panama Red",
               "spt": 7,
               "water": 9,
               "pr": 31,
               "planted": false
            }
         ],
         "water": 30,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 1,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "abztraxxx": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "audiomancer": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "cryptounicorn420": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "dolp": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "xplora4253": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "ricarox": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "edtorr704": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "marcoss21": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "foxon": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "meanbees": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "degranoengrano": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "ibanezense": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "ejmh": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "toxicmen01": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "cratic": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "criptojones": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "bigkidstuff": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "dominic23": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "electru": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "lozadakb": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "hodltoday": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "fdeflash": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "pedroozj": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "facugaba": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "luisveco88": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "aries02": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "medicenw1": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "quefe": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "mejiasclaudia": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "cadawg": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 1,
            "afghanistanUsed": 0,
            "southAmerica": 1,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 2,
         "seedCount": 2,
         "seeds": [
            {
               "name": "Colombian Gold",
               "spt": 7,
               "water": 10,
               "pr": 356,
               "planted": false
            },
            {
               "name": "Mazar I Sharif",
               "spt": 6,
               "water": 33,
               "pr": 1161,
               "planted": false
            }
         ],
         "water": 60,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 2,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "ecuaminte": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "abrockman": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "supremdsm": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "darthslaver": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "juanchuzx": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 1,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 1,
         "seedCount": 1,
         "seeds": [
            {
               "name": "Mazar I Sharif",
               "spt": 6,
               "water": 33,
               "pr": 831,
               "planted": false
            }
         ],
         "water": 30,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 1,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "dobro2020": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "dantejcs": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "the-mister7": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "reward.app": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "oblivioncubed": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "yoclensavilan": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 0,
         "seedCount": 0,
         "seeds": [],
         "water": 0,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "elprutest": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 1,
            "africaUsed": 0,
            "afghanistan": 1,
            "afghanistanUsed": 0,
            "southAmerica": 3,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 1,
            "mexicoUsed": 0
         },
         "plotCount": 6,
         "seedCount": 6,
         "seeds": [
            {
               "name": "Colombian Gold",
               "spt": 7,
               "water": 10,
               "pr": 281,
               "planted": false
            },
            {
               "name": "Panama Red",
               "spt": 7,
               "water": 9,
               "pr": 217,
               "planted": false
            },
            {
               "name": "Acapulco Gold",
               "spt": 6,
               "water": 23,
               "pr": 739,
               "planted": false
            },
            {
               "name": "Lashkar Gah",
               "spt": 5,
               "water": 43,
               "pr": 1413,
               "planted": false
            },
            {
               "name": "Malawi",
               "spt": 4,
               "water": 93,
               "pr": 3615,
               "planted": false
            },
            {
               "name": "Colombian Gold",
               "spt": 7,
               "water": 10,
               "pr": 238,
               "planted": false
            }
         ],
         "water": 180,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 6,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "khan.dayyanz": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 1,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 1,
         "seedCount": 1,
         "seeds": [
            {
               "name": "Panama Red",
               "spt": 7,
               "water": 9,
               "pr": 216,
               "planted": false
            }
         ],
         "water": 30,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 1,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "xbladex": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 0,
            "southAmericaUsed": 0,
            "jamaica": 1,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 1,
         "seedCount": 1,
         "seeds": [
            {
               "name": "Lamb’s Bread",
               "spt": 2,
               "water": 215,
               "pr": 9097,
               "planted": false
            }
         ],
         "water": 30,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 1,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      },
      "cireth": {
         "plots": {
            "asia": 0,
            "asiaUsed": 0,
            "africa": 0,
            "africaUsed": 0,
            "afghanistan": 0,
            "afghanistanUsed": 0,
            "southAmerica": 1,
            "southAmericaUsed": 0,
            "jamaica": 0,
            "jamaicaUsed": 0,
            "mexico": 0,
            "mexicoUsed": 0
         },
         "plotCount": 1,
         "seedCount": 1,
         "seeds": [
            {
               "name": "Colombian Gold",
               "spt": 7,
               "water": 10,
               "pr": 52,
               "planted": false
            }
         ],
         "water": 30,
         "waterCount": 0,
         "waterPlants": {
            "lvl1": 1,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "timeBoosters": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "lvl9": 0,
            "lvl10": 0
         },
         "recollectors": {
            "lvl1": 0,
            "lvl2": 0,
            "lvl3": 0,
            "lvl4": 0,
            "lvl5": 0,
            "lvl7": 0,
            "lvl8": 0,
            "vl9": 0,
            "lvl10": 0
         },
         "buds": 0,
         "xp": 0,
         "lvl": 1,
         "role": 1,
         "joints": {
            "splif": 0,
            "joint": 0,
            "cone": 0,
            "kiefJoint": 0,
            "waxJoint": 0,
            "blunt": 0
         },
         "MOTA": 0,
         "MOTAstake": 0
      }
   },
   "cs": {
      "50720589:khan.dayyanz": "khan.dayyanz purchased south america bundle",
      "50724018:cadawg": "cadawg purchased south america bundle",
      "50724023:cadawg": "cadawg purchased an afghanistan bundle",
      "50724146:xbladex": "xbladex purchased a jamaica bundle",
      "50724279:cireth": "cireth purchased south america bundle",
      "50727521:juanchuzx": "juanchuzx purchased an afghanistan bundle",
      "50728373:academialibertad": "academialibertad purchased south america bundle",
      "50728753:elprutest": "elprutest purchased south america bundle",
      "50728758:elprutest": "elprutest purchased south america bundle",
      "50729756:elprutest": "elprutest purchased a mexico bundle",
      "50729759:elprutest": "elprutest purchased an afghanistan bundle",
      "50729772:elprutest": "elprutest purchased an africa bundle",
      "50730893:elprutest": "elprutest purchased south america bundle"
   }
}